// packages/vue-cli-simple-with-prettier/src/App.vue
<template>
    <main>
      <header class="main-header">
        <img src="logo.svg" alt="Xebia" />
        <h1>CLI performance metrics</h1>
        <p>
          Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
          Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.
        </p>
      </header>

      <Table :report="report" />
    </main>


</template>

<script>
import Table from "./components/Table";
import "./main.css";

export default {
  name: "app",
  components: {
    Table
  },
  data() {
    return {
      report: []
    };
  },
  async created() {
    this.report = await (await fetch("report.json")).json();
  }
};
</script>

<style>
div {
  height: 100%;
}
</style>

// packages/angular-cli/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  report: Object;
  constructor(private http: HttpClient) {
    http.get('assets/report.json').subscribe(report => this.report = report)
  }
}

<main>
  <header class="main-header">
    <h1>CLI performance metrics</h1>
    <p>
      Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.
    </p>
  </header>

  <table *ngIf="report" class="measurement-table">
    <thead>
    <tr>
      <td></td>
      <td *ngFor="let metric of report['angular-cli'].metrics">{{metric.description}}</td>
    </tr>
    </thead>
    <tbody>
    <tr *ngFor="let stack of report | keys">
      <td><a href="{{'https://' + stack + '-dot-ruben-oostinga-speeltuin.appspot.com'}}">{{report[stack].name}}</a></td>
      <td *ngFor="let metric of report[stack].metrics">{{metric.displayValue}}</td>
    </tr>
    </tbody>
  </table>

  <footer class="main-footer">
    Made with ❤️ @ <a href="https://xebia.com/">Xebia</a>
  </footer>
</main>
